WIP

diff --git a/.github/workflows/deploy-backend.yml b/.github/workflows/deploy-backend.yml
--- a/.github/workflows/deploy-backend.yml
+++ b/.github/workflows/deploy-backend.yml
@@ -1,6 +1,6 @@
-name: Build backend
-run-name: Build Backend
-description: Will build the backend for the environment.
+name: Deploy Backend
+run-name: Deploy Backend
+description: Will deploy the backend to the environment.
 
 on:
   workflow_dispatch:
@@ -13,32 +13,14 @@ on:
           - dev
           - prod
 
-permissions: write-all
+permissions: read-all
 
 jobs:
-  build-backend:
-    runs-on: self-hosted
+  deploy-backend:
     environment: ${{ inputs.environment }}
-    container: 
-      image: ${{ vars.WORKFLOW_IMAGE_REPO }}:latest
-      volumes:
-        - /home/agent/.aws:/github/home/.aws
-        - /root/.cache/go-build:/root/.cache/go-build
-        - /go/pkg/mod:/go/pkg/mod
+    runs-on: self-hosted
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          sparse-checkout: |
-            backend
-
-      - name: Build backend
-        shell: bash
-        run: |
-          cd backend
-          make build
-
       - name: Determine type
         id: determine_type
         shell: bash
@@ -47,27 +29,55 @@ jobs:
         run: |
           TYPE="unknown"
           if [[ "${{ env.ENVIRONMENT }}" == "prod" ]]; then
-            TYPE="latest"
+              TYPE="latest"
+              SERVER_ADDRESS="q-backend.questionnaire.petersonv.click"
           elif [[ "${{ github.ref_name }}" == "develop" && "${{ env.ENVIRONMENT }}" == "dev" ]]; then
-            TYPE="experimental"
+              TYPE="experimental"
+              SERVER_ADDRESS="q-backend.dev.questionnaire.petersonv.click"
           else
-            # Assume feature branch: add random suffix
-            RANDOM_SUFFIX=$(head /dev/urandom | tr -dc a-z0-9 | head -c6)
-            TYPE="feature-${RANDOM_SUFFIX}"
+              echo "ERROR: Invalid environment: ${{ env.ENVIRONMENT }}"
+              exit 1
           fi
-          echo type: $TYPE
           echo "TYPE=$TYPE" >> $GITHUB_OUTPUT
+          echo "SERVER_ADDRESS=$SERVER_ADDRESS" >> $GITHUB_OUTPUT
 
-      - name: Create GitHub Release
-        id: create_release
-        uses: softprops/action-gh-release@v2
-        with:
-          name: Release ${{ github.ref_name }} ${{ steps.determine_type.outputs.TYPE }}
-          tag_name: ${{ steps.determine_type.outputs.TYPE }}
-          repository: ${{ github.repository }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          draft: false
-          prerelease: false
-          files: |
-            backend/bin/webserver
-          body: Release of backend version ${{ github.ref_name }} ${{ steps.determine_type.outputs.TYPE }}
+      - name: Setup SSH Key
+        shell: bash
+        env:
+          SSH_KEY: ${{ secrets.BACKEND_SERVICE_SSH_KEY }}
+        run: |
+          mkdir -p ~/.ssh
+          chmod 700 ~/.ssh
+          echo "$SSH_KEY" > ~/.ssh/id_ed25519
+          chmod 600 ~/.ssh/id_ed25519
+          
+      - name: Deploy Backend
+        shell: bash
+        env:
+          SERVER_ADDRESS: ${{ steps.determine_type.outputs.SERVER_ADDRESS }}
+          USER: q-user
+          ENV: ${{ inputs.environment }}
+        run: |
+          ssh -i ~/.ssh/id_ed25519 $USER@$SERVER_ADDRESS 'bash -s' <<EOF
+            echo inside the ssh session
+
+            GITHUB_TOKEN=`aws ssm get-parameter \
+              --name "q-github-token-${ENV}" \
+              --query "Parameter.Value" \
+              --output text 2>/dev/null`
+            test -n "$GITHUB_TOKEN" || {
+              echo "GITHUB_TOKEN not found. Aborting."
+              exit 1
+            }
+
+            systemctl stop q-webserver-${ENV}
+            mv /q/webserver /q/webserver.old
+            gh release download latest \
+              -R petersonvcode/questionnaire \
+              -p webserver \
+              -O /q/webserver \
+              --token "$GITHUB_TOKEN"
+            chmod +x /q/webserver
+            systemctl start q-webserver-${ENV}
+            rm -f /q/webserver.old
+          EOF
